config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Generates tweets paths
  resources :tweets do
    resources :likes
    resources :retweets
  end

  resources :follows, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
    resources :messages
  end

  get 'tweets/index'

  # This redirects user to tweets index after succesful login
  get '/user' => "tweets#index", :as => :user_root

  get '/search' => 'users#search', :as => 'search_user'
  
  get 'home/index'
  
  root "home#index"

  match 'users/:id' => 'users#show', via: :get
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
  belongs_to :recipient, :class_name => "User", :foreign_key => "recipient_id"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_receiver, only: [:new, :create]

  def new
    @message = Message.new
    
    received_by_current = current_user.received.where(sender_id: @receiver.id)
    sent_by_current = @receiver.received.where(sender_id: current_user.id)
    @messages = (sent_by_current + received_by_current).sort_by(&:created_at)    
  end

  def create
    @message = Message.new(message_params)
    
    @message.recipient_id = params[:recipient]     
    @message.sender_id = current_user.id

    if @message.save
      received_by_current = current_user.received.where(sender_id: params[:user_id])
      sent_by_current = @receiver.received.where(sender_id: current_user.id)

      @messages = (sent_by_current + received_by_current).sort_by(&:created_at)
      
      redirect_to new_user_message_path(@receiver.id)
    else
      flash[:notice] = @message.errors.full_messages.to_sentence
    end
  end

  private
    def message_params
      params.require(:message).permit(:message)
    end

    def set_receiver
      @receiver = User.find(params[:user_id])
    end
end

app/views/messages/new.html.erb
<div class="container">
  <nav class="navbar navbar-dark">
    <a class="navbar-brand font-weight-bold" href="/">
      <%= image_tag("twitter_logo.svg", width: 30, height: 30, :class => "d-inline-block align-top") %>
      Twitter
    </a>
    <div class="nav navbar-nav navbar-right">
      <div class="d-flex align-items-center">
        <%= link_to('Profile', user_path(current_user), :class => "btn btn-large btn-outline-primary" ) %>
        <%= link_to('Log out', destroy_user_session_path, :class => "text-danger ml-4", method: :delete ) %>
      </div>
    </div>
  </nav>

  <div class="row mb-4">
    <div class="col-md-12">
      <div class="row">
        <h2>Send a message</h2>
      </div>
      
      <div class="card gradient-border">
        <%= form_with(model: Message, url: user_messages_path(:recipient => params[:user_id]), local: true) do |f| %>
          <%= f.text_area :message, class: "form-control mb-2 no-border", id: "tweet-body-area", onkeyup: "countChars(this)", placeholder: "Type your message here..." %>
          <%= f.submit "Send", class: "btn btn-outline-primary float-right" %>
        <% end %>
      </div>
      <p id="char-counter"></p>    

      <div class="card gradient-border px-3">
        <% @messages.each do |message| %>
          <h5 class="text-primary"><%= message.sender.name %></h5>
          <h5><%= message.message %></h5>
        <% end %>
      </div>
      
      <!-- Check for model errors -->
      <% if @message.errors.any? %>
        <ul style="list-style-type: none;">
          <% @message.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

</div>

<script>
  function countChars(textarea) {
    const charCounter = document.getElementById("char-counter");
    const charQty = textarea.value.length;
    charCounter.innerHTML = `${charQty} / 280`;

    if (charQty <= 280) {
      charCounter.classList.add("text-success");
      charCounter.classList.remove("text-danger");
    } else {
      charCounter.classList.add("text-danger");
      charCounter.classList.remove("text-success");
    }
  }
</script>