config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Generates tweets paths
  resources :tweets do
    resources :likes
    resources :retweets
  end

  resources :follows, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
    resources :messages
  end

  get 'tweets/index'

  # This redirects user to tweets index after succesful login
  get '/user' => "tweets#index", :as => :user_root

  get '/search' => 'users#search', :as => 'search_user'
  
  get 'home/index'
  
  root "home#index"

  match 'users/:id' => 'users#show', via: :get
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, 
         :rememberable, :validatable, :confirmable

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :username, uniqueness: true, length: {minimum: 1}
  validates :name, length: {minimum: 1}

  has_many :tweets, dependent: :destroy
  
  has_many :follows, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed

  has_many :reverse_follows, foreign_key: "followed_id", class_name: "Follow", dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower

  has_many :likes, dependent: :destroy

  has_many :retweets, dependent: :destroy

  has_many :sent, :class_name => "Message", :foreign_key => "sent_id"
  has_many :received, :class_name => "Message", :foreign_key => "recipient_id"

  def following?(other_user)
    follows.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    follows.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    follows.find_by_followed_id(other_user.id).destroy
  end

  def feed
    Tweet.from_users_followed_by(self)
  end

  def get_profile_feed  
    Tweet.get_profile_feed(self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :following, :followers]
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def following
    @title = "Following"
    @users = @user.followed_users
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @users = @user.followers
    render 'show_follow'
  end

  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "You can't search with the empty field.") and return  
    else
      @parameter = params[:search].downcase

      if @parameter[0] == "@"
        @parameter = @parameter[1...-1]
      end

      @resultsUser = User.all.where("lower(name) LIKE :search OR lower(username) LIKE :search", search: "%#{@parameter}%")
      @resultsTweet = Tweet.all.where("lower(body) LIKE :search", search: "%#{@parameter}%")
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
      @tweets = @user.get_profile_feed
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/search.html.erb
<div class="container">
    <nav class="navbar navbar-dark">
        <a class="navbar-brand font-weight-bold" href="/">
            <%= image_tag("twitter_logo.svg", width: 30, height: 30, :class => "d-inline-block align-top") %>
            Twitter
        </a>
        <%= form_tag(search_user_path, :method => "get",   
            class: 'navbar-form navbar-left') do %>  
            <div class="input-group">  
                <%= search_field_tag :search, params[:search], placeholder: "Search for somebody", class: "form-control no-border" %>  
                <%= submit_tag "Search", :class => "btn btn-large btn-outline-primary" %> 
            </div>  
        <% end %>
        <div class="nav navbar-nav navbar-right">
            <div class="d-flex align-items-center">
                <%= link_to('Profile', user_path(current_user), :class => "btn btn-large btn-outline-primary" ) %>
                <%= link_to('Log out', destroy_user_session_path, :class => "text-danger ml-4", method: :delete ) %>
            </div>
        </div>
    </nav>

    <div class="row mb-4 mt-3">
        <div class="col-md-12 d-flex justify-content-center flex-column">
            <div class="mb-3">
                <h2 class="font-weight-bold">Search Result</h2>

                <h3>Users:</h3>
                <% if @resultsUser.size == 0 %>
                    <h3>No results</h3>
                <% else %>
                    <% @resultsUser.each do |result| %>
                        <div class="card gradient-border">
                            <div class="card-body text-center">
                                <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= result.id %>"><%= result.name %></a></h5>
                                <h6 class="card-subtitle text-muted">@<%= result.username %></h6>
                            </div>
                        </div>
                    <% end %>
                <% end %>

                <h3 class="mt-4">Tweets:</h3>
                <% if @resultsTweet.size == 0 %>
                    <h3>No results</h3>
                <% else %>
                    <div id="tweets" class="row mb-3">
                        <div class="col-md-12">
                        <% @resultsTweet.each do |tweet| %>
                            <div class="card gradient-border">
                            <div class="card-body">
                                <% retweeted_by_user = tweet.retweets.find { |retweet| retweet.user_id == current_user.id} %>

                                <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= tweet.user_id %>"><%= User.find(tweet.user_id).name %></a></h5>
                                <h6 class="card-subtitle text-muted">@<%= User.find(tweet.user_id).username %></h6>
                                <p class="card-subtitle text-muted" style="cursor: pointer;" data-toggle="tooltip" data-placement="top" title="<%= tweet.created_at.strftime("%T - %B %d %Y") %>"> - <%= tweet.created_at.strftime("%B %d") %></p>
                                
                                <% if retweeted_by_user && !tweet.quoted_tweet_id.present? %>
                                <h6 class="card-subtitle text-primary">Retweeted by me</h6>
                                <% else %>
                                <% if current_user.id != tweet.user.id && !current_user.following?(tweet.user) %>
                                    <h6 class="card-subtitle text-primary">Retweeted by someone you follow</h6>
                                <% end %>
                                <% end %>

                                <p class="card-text mt-3"><%= tweet.body %></p>

                                <% if tweet.quoted_tweet_id.present? %>
                                <% quoted_tweet = Tweet.find(tweet.quoted_tweet_id)%>
                                <div class="card gradient-border mb-3">
                                    <div class="card-body">
                                    <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= quoted_tweet.user_id %>"><%= User.find(quoted_tweet.user_id).name %></a></h5>
                                    <h6 class="card-subtitle text-muted">@<%= User.find(quoted_tweet.user_id).username %></h6>
                                    <p class="card-subtitle text-muted" style="cursor: pointer;" data-toggle="tooltip" data-placement="top" title="<%= quoted_tweet.created_at.strftime("%T - %B %d %Y") %>"> - <%= quoted_tweet.created_at.strftime("%B %d") %></p>
                                    <p class="card-text mt-3"><%= quoted_tweet.body %></p>
                                    </div>
                                </div>     
                                <% end %>  

                                <% if tweet.photo.attached? %>
                                <image class="w-75 mw-100 mb-4 d-block" src="<%=url_for(tweet.photo) %>" >
                                <% end %>
                                
                                <% its_liked = tweet.likes.find { |like| like.user_id == current_user.id} %>
                                <% if its_liked %>
                                <%= link_to 'Unlike', tweet_like_path(tweet, its_liked), method: :delete, class: "btn btn-outline-secondary" %>
                                <% else %>
                                <%= link_to 'Like', tweet_likes_path(tweet), method: :post, class: "btn btn-outline-primary" %>
                                <% end %>

                                
                                <% if retweeted_by_user %>
                                <%= link_to 'Unretweet', tweet_retweet_path(tweet, retweeted_by_user), method: :delete, class: "btn btn-outline-secondary" %>
                                <% else %>
                                
                                <%= link_to 'Retweet', tweet_retweets_path(tweet), method: :post, class: "btn btn-outline-primary" %>
                                
                                <% end %>

                                <%= link_to 'Quote', new_tweet_path(:quoted_tweet_id => tweet.id), class: "btn btn-outline-info" %>
                                
                                <% if current_user.id == tweet.user.id  %>
                                <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-warning" %>
                                <%= link_to 'Delete', tweet, method: 'delete', data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
                                <% end %>            

                                <p class="mt-3"><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'like' : 'likes'%></p>
                                <p class="mt-3"><%= tweet.retweets.count %> <%= (tweet.retweets.count) == 1 ? 'retweet' : 'retweets'%></p>

                                
                                <% quotesAmount = Tweet.where(quoted_tweet_id: tweet.id).count %>
                                <p class="mt-3"><%= quotesAmount %> <%= quotesAmount == 1 ? ' quote' : 'quotes' %></p>
                            
                            </div>
                            </div>
                        <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <nav class="navbar navbar-dark">
    <a class="navbar-brand font-weight-bold" href="/">
      <%= image_tag("twitter_logo.svg", width: 30, height: 30, :class => "d-inline-block align-top") %>
      Twitter
    </a>
    <%= form_tag(search_user_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
        <div class="input-group">  
            <%= search_field_tag :search, params[:search], placeholder: "Search for somebody", class: "form-control no-border" %>  
            <%= submit_tag "Search", :class => "btn btn-large btn-outline-primary" %> 
        </div>  
    <% end %>
    <div class="nav navbar-nav navbar-right">
      <div class="d-flex align-items-center">
        <%= link_to('Profile', user_path(current_user), :class => "btn btn-large btn-outline-primary" ) %>
        <%= link_to('Log out', destroy_user_session_path, :class => "text-danger ml-4", method: :delete ) %>
      </div>
    </div>
  </nav>

  <div class="row mb-4 mt-3">
    <div class="col-md-12 d-flex justify-content-center flex-column">
      <div class="text-center mb-3">
        <h1 class="font-weight-bold"><a class="text-white" href="/users/<%= @user.id %>"><%= @user.name %></a></h1>
        <h5 class="text-muted mb-3">@<%= @user.username %></h5>
        <div class="d-flex justify-content-center">
          <a class="mx-4" href="/users/<%= @user.id %>/following">
            <p class="">Following</p>
            <h2 class="font-weight-bold"><%= @user.followed_users.count %></h2>
          </a>
          <a class="mx-4" href="/users/<%= @user.id %>/followers">
            <p class="">Followers</p>
            <h2 class="font-weight-bold"><%= @user.followers.count %></h2>
          </a>
        </div>
        <% if @user.id != current_user.id %>
          <% if current_user.following?(@user) %>
            <%= form_for(current_user.follows.find_by_followed_id(@user), html: { method: :delete }) do |f| %>
              <%= f.submit "Unfollow", class: "btn btn-large btn-primary" %>
            <% end %>
          <% else %>
            <%= form_for(current_user.follows.build(followed_id: @user.id)) do |f| %>
              <div><%= f.hidden_field :followed_id %></div>
              <%= f.submit "Follow", class: "btn btn-large btn-outline-primary" %>
            <% end %>
          <% end %>
          <%= link_to 'Message', new_user_message_path(@user.id), class: "btn btn-outline-info mt-3" %>
        <% end %>        
      </div>
      <div id="tweets" class="row mb-3">
        <div class="col-md-12">
          <h2 class="font-weight-bold">Tweets</h2>
          <% @tweets.each do |tweet| %>
            <div class="card gradient-border">
              <div class="card-body">
                <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= tweet.user.id %>"><%= tweet.user.name %></a></h5>
                <h6 class="card-subtitle text-muted">@<%= tweet.user.username %></h6>
                <% if params[:id].to_i == current_user.id && tweet.user.id != current_user.id %>
                  <h6 class="card-subtitle text-primary">Retweeted by me</h6>
                <% end %>
                <p class="card-text mt-3"><%= tweet.body %></p>
                
                <% if tweet.quoted_tweet_id.present? %>
                <% quoted_tweet = Tweet.find(tweet.quoted_tweet_id)%>
                  <div class="card gradient-border mb-3">
                    <div class="card-body">
                      <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= quoted_tweet.user_id %>"><%= User.find(quoted_tweet.user_id).name %></a></h5>
                      <h6 class="card-subtitle text-muted">@<%= User.find(quoted_tweet.user_id).username %></h6>
                      <p class="card-subtitle text-muted" style="cursor: pointer;" data-toggle="tooltip" data-placement="top" title="<%= quoted_tweet.created_at.strftime("%T - %B %d %Y") %>"> - <%= quoted_tweet.created_at.strftime("%B %d") %></p>
                      <p class="card-text mt-3"><%= quoted_tweet.body %></p>
                    </div>
                  </div>              
                <% end %>

                <% if tweet.photo.attached? %>
                  <image class="w-75 mw-100 mb-4 d-block" src="<%= url_for(tweet.photo) %>" >
                <% end %>

                <% its_liked = tweet.likes.find { |like| like.user_id == current_user.id} %>
                <% if its_liked %>
                  <%= link_to 'Unlike', tweet_like_path(tweet, its_liked), method: :delete, class: "btn btn-outline-secondary" %>
                <% else %>
                  <%= link_to 'Like', tweet_likes_path(tweet), method: :post, class: "btn btn-outline-primary" %>
                <% end %>

                <% retweeted_tweet = tweet.retweets.find { |retweet| retweet.user_id == current_user.id} %>
                <% if retweeted_tweet %>
                  <%= link_to 'Unretweet', tweet_retweet_path(tweet, retweeted_tweet), method: :delete, class: "btn btn-outline-secondary" %>
                <% else %>
                  <%= link_to 'Retweet', tweet_retweets_path(tweet), method: :post, class: "btn btn-outline-primary" %>
                <% end %>

                

                <% if @user.id == current_user.id %>
                  <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-warning" %>
                  <%= link_to 'Delete', tweet, method: 'delete', data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
                <% end %>

                <p class="mt-3"><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'like' : 'likes'%></p>
                <p class="mt-3"><%= tweet.retweets.count %> <%= (tweet.retweets.count) == 1 ? 'retweet' : 'retweets'%></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <nav class="navbar navbar-dark">
    <a class="navbar-brand font-weight-bold" href="/">
      <%= image_tag("twitter_logo.svg", width: 30, height: 30, :class => "d-inline-block align-top") %>
      Twitter
    </a>
    <%= form_tag(search_user_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
        <div class="input-group">  
            <%= search_field_tag :search, params[:search], placeholder: "Search for somebody", class: "form-control no-border" %>  
            <%= submit_tag "Search", :class => "btn btn-large btn-outline-primary" %> 
        </div>  
    <% end %>
    <div class="nav navbar-nav navbar-right">
      <div class="d-flex align-items-center">
        <%= link_to('Profile', user_path(current_user), :class => "btn btn-large btn-outline-primary" ) %>
        <%= link_to('Log out', destroy_user_session_path, :class => "text-danger ml-4", method: :delete ) %>
      </div>
    </div>
  </nav>

  <div class="row mb-4 mt-3">
    <div class="col-md-12 d-flex justify-content-center flex-column">
      <div class="text-center mb-3">
        <h1 class="font-weight-bold"><a class="text-white" href="/users/<%= @user.id %>"><%= @user.name %></a></h1>
        <h5 class="text-muted mb-3">@<%= @user.username %></h5>
        <div class="d-flex justify-content-center">
          <a class="mx-4" href="/users/<%= @user.id %>/following">
            <p class="">Following</p>
            <h2 class="font-weight-bold"><%= @user.followed_users.count %></h2>
          </a>
          <a class="mx-4" href="/users/<%= @user.id %>/followers">
            <p class="">Followers</p>
            <h2 class="font-weight-bold"><%= @user.followers.count %></h2>
          </a>
        </div>
        <% if @user.id != current_user.id %>
          <% if current_user.following?(@user) %>
              <%= form_for(current_user.follows.find_by_followed_id(@user), html: { method: :delete }) do |f| %>
                  <%= f.submit "Unfollow", class: "btn btn-large btn-primary" %>
              <% end %>
          <% else %>
              <%= form_for(current_user.follows.build(followed_id: @user.id)) do |f| %>
                  <div><%= f.hidden_field :followed_id %></div>
                  <%= f.submit "Follow", class: "btn btn-large btn-outline-primary" %>
              <% end %>
          <% end %>
        <% end %>
      </div>
      
      <div class="row mb-3">
          <div class="col-md-12">
              <h2 class="font-weight-bold"><%= @title %></h2>
              <% @users.each do |user| %>
                <div class="card gradient-border">
                  <div class="card-body">
                    <h5 class="card-title font-weight-bold"><a class="text-white" href="/users/<%= user.id %>"><%= user.name %></a></h5>
                    <h6 class="card-subtitle text-muted">@<%= user.username %></h6>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>